### ISSUE TITLE
Network myNetworkName not found

### ISSUE THREAD

**Issue by QitmentX7** [zoltanersek/android-wifi-activity#7]
Hello friend i need your help! I try your code with this, but get message: Network myNetworkName not found.
My connection have WPA/WPA2. Great thanks in advanced for help!
public class MainActivity extends WifiActivity implements WifiBase.WifiBaseListener {

    @Override
    public int getSecondsTimeout() {
        return 10000;
    }

    @Override
    public Context getContext() {
        return this;
    }

    @Override
    public Activity getActivity() {
        return MainActivity.this;
    }

    @Override
    public String getWifiSSID() {

        return "coworking2";
    }

    @Override
    public String getWifiPass() {
        return "welcome11";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        handleWIFI();
    }
}

**Comment by QitmentX7** [comment]
Problem solved!

**Comment by zoltanersek** [comment]
Thank you for your contribution! Much appreciated

**Comment by QitmentX7** [comment]
Happy to help! I want add you to LinkedIn, please write it.
